### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by daweiyuanzhang** [michaelScopic/dotfiles#2]
![CleanShot 2023-09-08 at 17 04 21@2x](https://github.com/michaelScopic/dotfiles/assets/31055033/4ed2b45a-9e06-4883-afd3-a0ba0dac50c7)
Can I know which configuration item is the execution time? Thx.

**Comment by michaelScopic** [comment]
In `~/.config/starship.toml`, the `cmd_duration` module controls that.

The following enables it:

```toml
[cmd_duration]
disabled = false ## Enable (with 'false') or disable (with 'true')
min_time = 500   ## Minimum amount of time for this module to appear (in milliseconds)
format = 'underwent [$duration](bold yellow)'   ## How you want to format this module (appearance)
```

There is a wiki if you need help:

https://starship.rs/config/#command-duration

You can also DM me on discord if you need further help: `michael_scopic.zsh`

GitHub issues works as well, but I will most likely have late replies.
